server:
  port: 8080
  run_mode: debug
logger:
  level: debug
  file_path: ./logs/logs.log
  encoding: json
  type: zerolog
postgres:
  host: localhost
  port: 5432
  user: postgres
  password: admin
  db_name: car_bid_db
  ssl_mode: disable
redis:
  host: localhost
  port: 6379
  password: 123456
  db: 0
  dial_timeout: 5
  read_timeout: 5
  write_timeout: 5
  pool_size: 10
  pool_timeout: 15
  idle_check_frequency: 500
