version: "2"
sql:
  - engine: "postgresql"
    queries: "../internal/data/db/queries/"
    schema: "../internal/data/db/migrations/"
    gen:
      go:
        package: "sqlc"
        out: "../internal/data/db/sqlc"
        sql_package: "pgx/v5"
        emit_json_tags: true
        emit_prepared_queries: true
        emit_interface: true
        emit_exact_table_names: false
        overrides:
          # Non-null types
          - db_type: "uuid"
            go_type: "github.com/google/uuid.UUID"
          - db_type: "timestamp"
            go_type: "time.Time"
          - db_type: "timestamptz"
            go_type: "time.Time"
          - db_type: "numeric"
            go_type: "float64"

          # Nullable types
          - db_type: "uuid"
            go_type: "github.com/google/uuid.NullUUID"
            nullable: true
          - db_type: "text"
            go_type: "database/sql.NullString"
            nullable: true
          - db_type: "integer"
            go_type: "database/sql.NullInt32"
            nullable: true
          - db_type: "numeric"
            go_type: "database/sql.NullFloat64"
            nullable: true
          - db_type: "timestamp"
            go_type: "database/sql.NullTime"
            nullable: true
          - db_type: "timestamptz"
            go_type: "database/sql.NullTime"
            nullable: true
