version: "2"
sql:
  - engine: "postgresql"
    queries: "../internal/data/db/queries/"
    schema: "../internal/data/db/migrations/"
    gen:
      go:
        package: "sqlc"
        out: "../internal/data/db/sqlc"
        sql_package: "pgx/v5"
        emit_json_tags: true
        emit_prepared_queries: true
        emit_interface: true
        emit_exact_table_names: false
        overrides:
          - db_type: "timestamptz"
            go_type: "time.Time"
